### ISSUE TITLE
jniLib只有armeabi的么？

### ISSUE THREAD

**Issue by maxdylan** [runner365/android_rtmppush_sdk#17]
我查了一下我的机器指令集是AArch64，百度了一下，cup型号好像是ARMv8的，是不是就不能用你这个sdk了咧？

**Comment by ICECHN** [comment]
同问，能否提供一下其他如armeabi-v7a的库？

**Comment by liangsaifei** [comment]
这一个库就可以 跑在二位手机上没问题，对v7a 和64的是兼容的。
