### ISSUE TITLE
视频延迟超过7秒

### ISSUE THREAD

**Issue by chenxiaojin** [runner365/android_rtmppush_sdk#19]
你好， 我现在用你的这个推流的库， 实测延迟是有7秒以上， 我接受视频数据不是用的摄像头， 是其他设备， 我接受到的数据直接透传到rtmp服务器。所以sps，pps我一开始并没有发， 是不是因为一开始没有sps，pps， 所以无法解析， 等到接受了sps， pps后就能解析了？ 或者是rtmp sdk有做延迟的配置？

**Comment by GQii** [comment]
我和你碰到了同样的问题，你现在解决了吗？怎么解决了？

**Comment by chenxiaojin** [comment]
> 我和你碰到了同样的问题，你现在解决了吗？怎么解决了？

好像不是推流的问题， 是播放的问题。 原来我用的是电脑vlc播放， 这个一直会有延迟。你可以换android端的EasyPlayer去试试。
