### ISSUE TITLE
######fail to get PCM data ，?? 

### ISSUE THREAD

**Issue by li2014** [runner365/android_rtmppush_sdk#2]
I/MyStreamActivity: Listing all supported preview sizes
 I/MyStreamActivity:   w: 1920, h: 1080
 I/MyStreamActivity:   w: 1600, h: 1200
 I/MyStreamActivity:   w: 1280, h: 768
 I/MyStreamActivity:   w: 1280, h: 720
 I/MyStreamActivity:   w: 1024, h: 768
 I/MyStreamActivity:   w: 800, h: 600
 I/MyStreamActivity:   w: 800, h: 480
 I/MyStreamActivity:   w: 720, h: 480
 I/MyStreamActivity:   w: 640, h: 480
 I/MyStreamActivity:   w: 352, h: 288
 I/MyStreamActivity:   w: 320, h: 240
 I/MyStreamActivity:   w: 176, h: 144
 I/MyStreamActivity: Listing all supported preview formats
 I/MyStreamActivity: preview formats:842094169
 I/MyStreamActivity: preview formats:17
 I/MyStreamActivity: MainActivity onDestroy...
 E/AudioRecord: start() status -38
 I/Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread.
I/MyStreamActivity: ######fail to get PCM data
I/MyStreamActivity: ######fail to get PCM data
I/MyStreamActivity: ######fail to get PCM data
I/MyStreamActivity: ######fail to get PCM data
I/MyStreamActivity: ######fail to get PCM data
I/MyStreamActivity: ######fail to get PCM data
I/MyStreamActivity: ######fail to get PCM data

**Comment by runner365** [comment]
It means it didn't get the pcm data from the mic. please check whether your phone is opend mic right for tha app demo.
